### ISSUE TITLE
Unable to send messages

### ISSUE THREAD

**Issue by ContourCode** [micahlt/modchat-server#10]
After being signed in and having Modchat closed for a long period of time, when I open Modchat again, I am unable to post messages until I sign out and sign back in again.

**Comment by ghost** [comment]
This is likely the result of the TensorFlow not being encapsulated inside of modchat-server. Instead, modchat-server pings a replit.com instance hosting the TensorFlow filter.

Encapsulating the TensorFlow filter inside modchat-server should fix this and provide a significant speed increase as you are going from replit to Heroku.

**Comment by iamperry294** [comment]
There is also a possibility that this is because of socket reconnects being fixed, which just means you have to reload. But since you have to logout for it to work, it's probably the TensorFlow.

**Comment by ghost** [comment]
Fixed in [```b349c35```](https://github.com/micahlt/modchat-server/commit/b349c353e8ad4f3ce5ef85576f667a8163ff72a0).
