### ISSUE TITLE
Switch to npm package `badwords-filter`

### ISSUE THREAD

**Issue by micahlt** [micahlt/modchat-server#12]
Switching to the npm package [`badwords-filter`](https://www.npmjs.com/package/badwords-filter) will make our text filtering much more advanced, including the ability of detecting 0s and 3s plus special characters!  This should be an almost drop-in replacement, just have to get around to it.

**Comment by xeonstaff** [comment]
yo, I can help

**Comment by micahlt** [comment]
You're very welcome to make a pull request!  You'll want to work on the `dev` branch in the `filter.js` file (see [here](https://github.com/micahlt/modchat-server/blob/dev/filter.js)) - as far as I've seen from the docs, the `badwords-filter` package should be a drop-in replacement for `bad-words`, so it shouldn't be hard!

**Comment by ghost** [comment]
Fixed in [```be0e569```](https://github.com/micahlt/modchat-server/commit/be0e569392937e14c97a6dc3ddddc82fe7d490ab).
