### ISSUE TITLE
Add moderation features

### ISSUE THREAD

**Issue by ghost** [micahlt/modchat-server#13]
Since ModChat is supposed to be moderated, moderation needs to be added. Here's what needs to be done:

## **Backend**
- [x] https://github.com/micahlt/modchat-server/commit/afd0e14d29a79d7e0b9a756e18ec2f3e64b8e9ff Revoke session endpoint
- [x] https://github.com/micahlt/modchat-server/commit/afd0e14d29a79d7e0b9a756e18ec2f3e64b8e9ff Ban endpoint
- [x] https://github.com/micahlt/modchat-server/commit/afd0e14d29a79d7e0b9a756e18ec2f3e64b8e9ff Unban endpoint
- [x] https://github.com/micahlt/modchat-server/commit/afd0e14d29a79d7e0b9a756e18ec2f3e64b8e9ff Delete message endpoint
- [x] https://github.com/micahlt/modchat-server/commit/afd0e14d29a79d7e0b9a756e18ec2f3e64b8e9ff Mute and Unmute endpoint
- [x] https://github.com/micahlt/modchat-server/commit/afd0e14d29a79d7e0b9a756e18ec2f3e64b8e9ff An endpoint to tell if a user is banned
- [x] https://github.com/micahlt/modchat-server/commit/0c30d49582f496ca7757cfdce8a878f4a38ad06a Report and Unreport a message endpoint
- [x] https://github.com/micahlt/modchat-server/commit/0c30d49582f496ca7757cfdce8a878f4a38ad06a Endpoint to show all reported messages 
- [x] https://github.com/micahlt/modchat-server/commit/2ebdd668bb59a9ee07c344279ed16101b5d9f12a and https://github.com/micahlt/modchat-server/commit/0c30d49582f496ca7757cfdce8a878f4a38ad06a Implement banning and unbanning checks
- [x] https://github.com/micahlt/modchat-server/commit/afd0e14d29a79d7e0b9a756e18ec2f3e64b8e9ff Authorization for all endpoints 
- [x] https://github.com/micahlt/modchat-server/commit/4aca7e488bb556c3f0e1f239b55639c1893953ac Implement muted and unmuted checks (Low Priority)
- [x] https://github.com/micahlt/modchat-server/commit/4aca7e488bb556c3f0e1f239b55639c1893953ac Implement automute (Low Priority)
- [x] https://github.com/micahlt/modchat-server/commit/1b5b8dd69dc2bcf6b77ccdc3c3bb634fa8e2b397 Endpoint for if a user is a moderator (used to hide or show modpanel)

## **Frontend**
- [x] https://github.com/micahlt/modchat-vue/commit/9c58f7263d29cd4e61bb86ef71e3ce2b6b805941 Handle banning and unbanning while using the isBanned endpoint
- [x] https://github.com/micahlt/modchat-server/commit/4aca7e488bb556c3f0e1f239b55639c1893953ac Mute and Unmute support
- [x] Reporting a message

## **ModPanel**
- [x] Make the page design and add authorization to the panel
- [x] Implement banning users
- [x] Implement unbanning users
- [x] Be able to mute users for as long as possible
- [x] Being able to unmute users 
- [x] Be able to revoke a session for any user
- [x] Have the ability to report a message, delete a message, and make a message no longer be reported
- [x] Be able to check if a user is banned or not
- [x] Be able to look at reported messages and look at full message logs

Any other suggestions would be appreciate and please let me know.

**Comment by mistysloth** [comment]
Admin Panel Concept; Sorry it was rushed.
![modchatadminconcept](https://user-images.githubusercontent.com/93560458/164580609-b618993f-a0f0-44d0-bd4a-4825ead14ff9.png)

**Comment by ghost** [comment]
@SecretAgent55 Interesting, but we have our own concepts now.

@micahlt, Do you want to publish the designs?
