### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by jessiejs** [micahlt/modchat-server#15]
I don't know if this is just a problem with me since I am an old user, but on all platforms, I can't sign into my modchat account, and I can't create an account, or login, as no matter what it says "make sure you signed up with scratch".

I know, how dare i sign up before I have even signed up. boiHeh.

**Comment by ghost** [comment]
This is a frontend issue. Please make an issue in [Modchat Vue](https://github.com/micahlt/modchat-vue).
