### ISSUE TITLE
Arbitrary Password Resets

### ISSUE THREAD

**Issue by AmazingMech2418** [micahlt/modchat-server#16]
Password resets aren't authenticated. Someone could easily just reset someone else's password and nobody can stop them.

**Comment by micahlt** [comment]
That's... an issue.  Have you tested this?

**Comment by AmazingMech2418** [comment]
I changed your password to "test".

**Comment by jessiejs** [comment]
I suggest we do a quick fix for now to fix this ASAP where we just temporarily disable password resets.

**Comment by CodeLikeCrazE** [comment]
I made a PR #17 that actually fixes this.
