### ISSUE TITLE
DoS due to lack of sanitation

### ISSUE THREAD

**Issue by AmazingMech2418** [micahlt/modchat-server#2]
This bug carries over from previous versions of ModChat, as well as all of the forks of that version, and can be fixed in a similar way.

When receiving socket.io messages, the server does not check to make sure that requested properties are found in the data object, and therefore, errors may be thrown during this, crashing the server.

While the socket is private, and I cannot personally find out how to forge a request to send a message given a token, it still can be used for this DoS system.

Simply copy the socket.io-client code from https://github.com/socketio/socket.io-client/blob/master/dist/socket.io.min.js and then type in the following code:
```js
io(serverHost).emit("chat")
```

Once you do this, ModChat's server will crash.

**Comment by micahlt** [comment]
Appreciate the issue!  I'll work on this as soon as I get a chance.  Of course if you'd like to implement a fix I'd love to see a PR 😄

**Comment by AmazingMech2418** [comment]
I can possibly add a PR for this and #3 tomorrow if I have the chance!

**Comment by micahlt** [comment]
Sounds awesome!  Looks like you'll be the first outside contributor to MCv2!

**Comment by micahlt** [comment]
Fixed in d60c6ecacad7e4dfac07fc29ef7ef8d4e09ff82f.
