### ISSUE TITLE
Mentions

### ISSUE THREAD

**Issue by micahlt** [micahlt/modchat-server#9]
@mentions should notify the mentioned user via a notification when Modchat is not running (perhaps through the service worker?).  This should be a passive API that is polled every five minutes or so, not a socket instance.  When Modchat is running, it should send a notification and highlight the message with CSS.

**Comment by micahlt** [comment]
Partially done in https://github.com/micahlt/modchat-vue/commit/5536af7004d88119e776158ab61924ff06fe9cb4.  However, we're still deciding whether or not to do passive mentions through the service worker.

**Comment by ghost** [comment]
Doing passive mentions seems like a waste, even if it's opt-in. A user would have to be on ModChat before, right? Perhaps the user doesn't want to be on ModChat or can't. Yes, it is opt-in, but it doesn't seem like it would be very useful. If you saw that someone mentioned you and you weren't on ModChat, that could be a problem if 100 messages had passed. If that happens, you can't see the message anymore.

**Comment by AmazingMech2418** [comment]
Why would you use a service worker? Wouldn't a simple notification-storing system work better?

**Comment by micahlt** [comment]
@AmazingMech2418 Using a service worker takes the responsibility for storing messages from the server to the client, which helps keep server costs low.

**Comment by AmazingMech2418** [comment]
@micahlt Doesn't that only work if the device is on though, and when the browser is open for some devices? In my opinion, a service worker wouldn't be a good solution to creating a way to receive notifications when offline due to such limitations.

**Comment by micahlt** [comment]
@AmazingMech2418 That's a fair point.  However, there's been some pushback on the whole concept of notifications anyway, so this issue is temporarily at a standstill until we get security and moderation finished.
